version: '3.3'
services:
  qinglong: 
    image: whyour/qinglong:latest
    container_name: qinglong
    environment:
    volumes:
- "pwd-pvc:/ql/config"
- "pwd-pvc:/ql/log"
- "pwd-pvc:/ql/db"
- "pwd-pvc:/ql/scripts"
- "pwd-pvc:/ql/jbot"
- "pwd-pvc:/ql/repo"
    ports:    
      - "5700:5700"
      
volumes:
  pwd:
    driver_opts:
      class: csi-okteto-standard
