version: '3.3'
services:
  qinglong: 
    image: whyour/qinglong:latest
    container_name: qinglong
    environment:
    volumes:
      - "pwd-pvc:/ql"
    ports:    
      - "5700:5700"
      
volumes:
  pwd-pvc:
    driver_opts:
      class: csi-okteto-standard
